add mapping names
GenerationSoftware/pt-v5-prize-pool pull request #59
Opened 2023-09-07 16:59 UTC by trmid

2023-09-07 21:22 UTC, PierrickGT requested changes

2023-09-07 21:22 UTC, PierrickGT commented on src/PrizePool.sol
>    /// @dev vault => account => drawId => tier => prizeIndex => claimed
Can be removed.

2023-09-07 21:22 UTC, PierrickGT commented on src/libraries/DrawAccumulatorLib.sol
> +    mapping(uint256 drawId => Observation observation) observations;
This isn't the `drawId` here since it is supposed to be `uint24`.
It is the id of the observation which increase incrementally.

2023-09-07 22:57 UTC, trmid commented on src/libraries/DrawAccumulatorLib.sol
> +    mapping(uint256 drawId => Observation observation) observations;
This is the drawId. We use uint256 instead of uint24 because it saves gas here.

2023-09-07 23:01 UTC, trmid commented on src/PrizePool.sol
>    /// @dev vault => account => drawId => tier => prizeIndex => claimed
Well sure, but the point of these names is to be explicit in intention for the values in a mapping. I get that "DrawAccumulatorLib.Accumulator" doesn't really need any extra explanation, but an `address` should be explicitly named.

2023-09-08 01:11 UTC, trmid commented on src/libraries/DrawAccumulatorLib.sol
> +    mapping(uint256 drawId => Observation observation) observations;
Removed the redundant name here: [b9cb204](https://github.com/GenerationSoftware/pt-v5-prize-pool/pull/59/commits/b9cb204075518d11a881261f649060dc5910260c)

2023-09-08 01:12 UTC, trmid commented on src/PrizePool.sol
>    /// @dev vault => account => drawId => tier => prizeIndex => claimed
Removed redundant naming here: [b9cb204](https://github.com/GenerationSoftware/pt-v5-prize-pool/pull/59/commits/b9cb204075518d11a881261f649060dc5910260c)

2023-09-08 16:56 UTC, PierrickGT commented on src/PrizePool.sol
>    /// @dev vault => account => drawId => tier => prizeIndex => claimed
The comment `/// @dev vault => account => drawId => tier => prizeIndex => claimed` can be removed, not `accumulator`.

2023-09-08 18:40 UTC, merged