Auctions allocate fees instead of withdraw reserve
GenerationSoftware/pt-v5-prize-pool pull request #69
Opened 2023-09-21 01:45 UTC by trmid

2023-09-21 21:10 UTC, PierrickGT requested changes

2023-09-21 21:10 UTC, PierrickGT commented on test/PrizePool.t.sol
> +  event WithdrawRewards(address indexed to, uint256 amount, uint256 available);
We can also log `msg.sender` here.

2023-09-21 21:10 UTC, PierrickGT commented on test/PrizePool.t.sol
> +    // (if they aren't anyone can call contributePrizes with the unaccounted fee amount and basically take it as their own)
I think you meant `contributePrizeTokens`.
```suggestion
    // (if they aren't anyone can call contributePrizeTokens with the unaccounted fee amount and basically take it as their own)
```

2023-09-21 22:42 UTC, trmid commented on test/PrizePool.t.sol
> +  event WithdrawRewards(address indexed to, uint256 amount, uint256 available);
resolved with: [17ad8cc](https://github.com/GenerationSoftware/pt-v5-prize-pool/pull/69/commits/17ad8cc2f00a67133ea3c260eaa566ea41c328ff)

2023-09-21 22:42 UTC, trmid commented on test/PrizePool.t.sol
> +    // (if they aren't anyone can call contributePrizes with the unaccounted fee amount and basically take it as their own)
resolved with: [17ad8cc](https://github.com/GenerationSoftware/pt-v5-prize-pool/pull/69/commits/17ad8cc2f00a67133ea3c260eaa566ea41c328ff)

2023-09-22 21:08 UTC, PierrickGT approved these changes

2023-09-25 18:47 UTC, merged