Fix prize contribution period
GenerationSoftware/pt-v5-prize-pool pull request #72
Opened 2023-09-29 22:38 UTC by trmid

2023-10-02 20:46 UTC, PierrickGT requested changes

2023-10-03 19:23 UTC, trmid commented on src/PrizePool.sol
> +  /// @dev First draw period has an ID of `1`. This means that if `_lastClosedDrawId` is zero,
This is making a comment on how `_currentDrawId()` will never return zero, so if we see that `_lastClosedDrawId` *is* zero, we know that there haven't been any closed draws yet.

2023-10-03 19:27 UTC, trmid commented on src/PrizePool.sol
> +      _getTotalContributedBetween(_lastClosedDrawId + 1, _openDrawId())
This computes all the contributions since the last closed draw until (and including) the open draw. We need to add 1 to `_lastClosedDrawId` since the `_getTotalContributedBetween` function has inclusive bounds on both sides.

I would argue against a helper function since it would add more gas and LOC.

2023-10-03 19:29 UTC, trmid commented on src/PrizePool.sol
> +    if (block.timestamp >= _drawEndsAt(lastClosedDrawId_ + 1)) {
Yeah, that's how it would work. It shouldn't be an issue since the claims are configured to reach max fees by the end of the initial period.

2023-10-03 19:35 UTC, trmid commented on src/PrizePool.sol
> +    return (currentDrawId_ - _lastClosedDrawId) > 1 ? currentDrawId_ - 1 : currentDrawId_;
If any amount of draws are missed, the open draw will always "lag" behind the current draw by 1. This ensures that it can always be closed once the system has recovered.

We no longer increment draws by 1 when a period is skipped, so in this case the open draw would be `9`. If it were to be closed, we would have skipped 1 draw (#8). Once closed, our newly opened draw would "catch up" to our current draw, which is `#10`, and draws would continue as normal.

2023-10-03 19:39 UTC, trmid commented on src/abstract/TieredLiquidityDistributor.sol
> +  uint48 public lastClosedDrawAwardedAt;
used in the claimer here: https://github.com/GenerationSoftware/pt-v5-claimer/blob/7c24e4171d5eb506a425ff4030f830baabdfbcb6/src/Claimer.sol#L252

2023-10-03 19:44 UTC, trmid commented on src/libraries/DrawAccumulatorLib.sol
>      if (_endDrawId < drawIds.second - 1) {
Both `_startDrawId` and `_endDrawId` are inclusive and noted as such in the natspec: https://github.com/GenerationSoftware/pt-v5-prize-pool/pull/72/files/ad748badc1ae3364f113de5e110e919f8a36903c#diff-3398ffb061aa112967b4fca69cb5301383c3306c54dfe4a0cff4b267431c08c2R172-R173

Where are we naming things with the `_Inclusive` postfix? I don't remember seeing this anywhere.

2023-10-03 19:57 UTC, PierrickGT commented on src/libraries/DrawAccumulatorLib.sol
>      if (_endDrawId < drawIds.second - 1) {
Here for example: https://github.com/GenerationSoftware/pt-v5-prize-pool/blob/ad748badc1ae3364f113de5e110e919f8a36903c/src/PrizePool.sol#L568

2023-10-03 20:14 UTC, trmid commented on test/PrizePool.t.sol
> +    console2.log(prizePool.getOpenDrawId());
fixed here: [62c6475](https://github.com/GenerationSoftware/pt-v5-prize-pool/pull/72/commits/62c6475d17f8e5889520f96ad5204b8c0bfad76f)

2023-10-03 20:14 UTC, trmid commented on test/PrizePool.t.sol
> +    console2.log(firstDrawStartsAt + drawPeriodSeconds);
fixed here: [62c6475](https://github.com/GenerationSoftware/pt-v5-prize-pool/pull/72/commits/62c6475d17f8e5889520f96ad5204b8c0bfad76f)

2023-10-03 20:14 UTC, trmid commented on test/invariants/helpers/TieredLiquidityDistributorFuzzHarness.sol
>      // console2.log("nextDraw", nextNumTiers, liquidity);
fixed here: [62c6475](https://github.com/GenerationSoftware/pt-v5-prize-pool/pull/72/commits/62c6475d17f8e5889520f96ad5204b8c0bfad76f)

2023-10-03 20:14 UTC, trmid commented on test/PrizePool.t.sol
> +    assertApproxEqAbs(prizePool.getTierRemainingLiquidity(0), 10e18 + 9e18, 10000);
added here: [d4b4180](https://github.com/GenerationSoftware/pt-v5-prize-pool/pull/72/commits/d4b41808ad3e0a5a5a721626ed39e9ab773954e1)

2023-10-03 20:15 UTC, trmid commented on src/libraries/DrawAccumulatorLib.sol
>      if (_endDrawId < drawIds.second - 1) {
Ah, we could add it for a consistent interface, but I think this falls out of scope for this PR.

2023-10-03 20:17 UTC, trmid commented on src/PrizePool.sol
> +    uint48 _endTimestamp = SafeCast.toUint48(_drawEndsAt(_lastClosedDrawId));
Doesn't look like we need it anymore since `_drawEndsAt` will throw an overflow error if the value exceeds uint48.

Removed here: [b38dac4](https://github.com/GenerationSoftware/pt-v5-prize-pool/pull/72/commits/b38dac40ab5cf2dc45545ebcd8e9af748834fde2)

2023-10-03 20:17 UTC, trmid commented on src/PrizePool.sol
> +  /// @dev The open draw is the next draw that can be closed.
Fixed here: [d4694d5](https://github.com/GenerationSoftware/pt-v5-prize-pool/pull/72/commits/d4694d53bfe36b067d5eb2768e1cb540e14e25ec)

2023-10-03 20:46 UTC, asselstine requested changes
Refactor naming:

current -> open

2023-10-03 20:46 UTC, asselstine commented on src/PrizePool.sol
> +    return _drawStartsAt(_openDrawId());
wondering if we should generalize these functions as `drawStartAt`, `drawEndAt` so that we can pass in the open / closing draw ids

2023-10-03 20:46 UTC, asselstine commented on src/PrizePool.sol
> +  function getOpenDrawId() external view returns (uint24) {
I think we need to expose the `closing` draw id as well

2023-10-03 20:46 UTC, asselstine commented on src/PrizePool.sol
> +    uint24 currentDrawId_ = _currentDrawId();
openDrawId

2023-10-03 20:46 UTC, asselstine commented on src/PrizePool.sol
> +    uint24 openDrawId_ = _openDrawId();
closingDrawId

2023-10-03 20:46 UTC, asselstine commented on src/PrizePool.sol
> +      openDrawId_,
closingDrawId

2023-10-03 20:46 UTC, asselstine commented on src/PrizePool.sol
> +  function _currentDrawId() internal view returns (uint24) {
open

2023-10-03 20:46 UTC, asselstine commented on src/PrizePool.sol
> +  function _openDrawId() internal view returns (uint24) {
closingDrawId

2023-10-05 16:38 UTC, PierrickGT requested changes

2023-10-05 16:38 UTC, PierrickGT commented on src/PrizePool.sol
> +  /// @notice Returns the time at which a draw opens.
It returns the timestamp at which a draw opens or opened right?
It can also be used to retrieve the timestamp at which the draw opened.
Would be useful to mention it.

2023-10-05 16:38 UTC, PierrickGT commented on src/PrizePool.sol
> +  /// @notice Returns the time at which a draw closes.
Same remark about the possibility of using this function to retrieve the timestamp at which the draw closed.

2023-10-05 16:38 UTC, PierrickGT commented on src/PrizePool.sol
> +  function isFinalized(uint24 drawId) external view returns (bool) {
I would have named it `isDrawFinalized`, so it's clear we are referring to the Draw being finalized.

2023-10-05 17:31 UTC, asselstine approved these changes

2023-10-05 18:47 UTC, PierrickGT approved these changes

2023-10-05 19:55 UTC, merged